-- MySQL Script generated by MySQL Workbench
-- Sat Apr  1 10:12:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tpjee_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpjee_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpjee_db` DEFAULT CHARACTER SET utf8 ;
USE `tpjee_db` ;

-- -----------------------------------------------------
-- Table `tpjee_db`.`Auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjee_db`.`Auteur` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NULL DEFAULT NULL,
  `prenom` VARCHAR(50) NULL DEFAULT NULL,
  `nationalite` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpjee_db`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjee_db`.`Document` (
  `ISBN` VARCHAR(50) NOT NULL,
  `libelle` VARCHAR(50) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `domaine` VARCHAR(50) NULL DEFAULT NULL,
  `auteur` INT(11) NOT NULL,
  `maisonEdition` INT(11) NOT NULL,
  `type` INT(11) NOT NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `ISBN` (`ISBN` ASC) VISIBLE,
  INDEX `auteur` (`auteur` ASC) VISIBLE,
  INDEX `maisonEdition` (`maisonEdition` ASC) VISIBLE,
  INDEX `type` (`type` ASC) VISIBLE,
  CONSTRAINT `document_ibfk_1`
    FOREIGN KEY (`auteur`)
    REFERENCES `tpjee_db`.`auteur` (`id`),
  CONSTRAINT `document_ibfk_2`
    FOREIGN KEY (`maisonEdition`)
    REFERENCES `tpjee_db`.`maisonedition` (`id`),
  CONSTRAINT `document_ibfk_3`
    FOREIGN KEY (`type`)
    REFERENCES `tpjee_db`.`typedocument` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpjee_db`.`Exemplaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjee_db`.`Exemplaire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codeExp` VARCHAR(30) NULL DEFAULT NULL,
  `documentID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codeExp` (`codeExp` ASC) VISIBLE,
  INDEX `documentID` (`documentID` ASC) VISIBLE,
  CONSTRAINT `exemplaire_ibfk_1`
    FOREIGN KEY (`documentID`)
    REFERENCES `tpjee_db`.`document` (`ISBN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpjee_db`.`MaisonEdition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjee_db`.`MaisonEdition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomMaison` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpjee_db`.`noms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjee_db`.`noms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  `prenom` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpjee_db`.`TypeDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpjee_db`.`TypeDocument` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
